language: node_js

node_js:
  - '6'

notifications:
  email:
    on_success: change
    on_failure: always

# Use container-based Travis infrastructure.
sudo: required
dist: trusty

addons:
  chrome: stable
  firefox: "latest"  

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jobs:
  include:
    - script: npm run lint
    - script: ./scripts/travis/test.sh
    - stage: build
      script:
        - npm run build
        - npm run test:package
    - stage: deploy
      script:
        - npm run build
        - ./scripts/travis/check-version.js
        - echo "Would deploy here"
