language: node_js

node_js:
  - '6'

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: change
    on_failure: always

# Use container-based Travis infrastructure.
sudo: required
dist: trusty

env:
  - CXX=g++-4.8z
addons:
  firefox: "latest"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

addons:
  at:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jobs:
  include:
    - stage: Test
      script: npm run lint
    - stage: Test
      script: ./scripts/travis/test.sh
    - stage: Build
      script:
        - npm run build
        - npm run test:package
    - stage: Deploy
      script: 
        - ./scripts/travis/check-version.js
        - echo "Would deploy here"
