language: node_js

node_js:
  - '6'
  - '8'

notifications:
  email:
    on_success: change
    on_failure: always

# Use container-based Travis infrastructure.
sudo: required
dist: trusty

env:
  - CXX=g++-4.8
addons:
  firefox: "latest"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

addons:
  at:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jobs:
  include:
    - stage: Build
      script: npm run build
    - stage: Test
      script: npm run lint
    - stage: Test
      script: npm run test:ci
    - stage: Test
      script: npm run test:package
    - stage: Check Versions
      script: ./scripts/release/check-version.js
